GAME_ROOM = "game::room"
GAME_START = "game::start"
GAME_STATE = "game::state"
GAME_NOTIFY = "game::notify"
GAME_PLAY = "game::play"
GAME_DRAW = "game::draw"
GAME_UNO = "game::uno"
GAME_OVER = "game::over"
SESSION_INFO = "session::info"

PLAYER_JOIN = "player::join"
PLAYER_READY = "player::ready"
PLAYER_TRANSFER_HOST = "player::transfer-host"
PLAYER_LEAVE = "player::leave"
